---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: vaultwarden
  interval: 1h
  values:
    controllers:
      vaultwarden:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: latest
            env:
              TZ: "America/New_York"
              DOMAIN: "https://vault.${SECRET_DOMAIN}"
              SIGNUPS_ALLOWED: "false"
              WEBSOCKET_ENABLED: "true"
            envFrom:
              - secretRef:
                  name: vaultwarden-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: vaultwarden
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "vault.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 80
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: longhorn
        globalMounts:
          - path: /data
