apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: media
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:T1RfXIty/E0u2ga/z9MJCGY4Ejk3WflijcCoVnBFdlNeh3xHWQrnTOYt69CExBORkFn/2cZJ6SL/StsZOybe+w==,iv:QTwV0Egi6japE06AJCjiGsXHFFjJX7udchrMkGXWIgI=,tag:YY/hSCCNGdz1EIjic9wYuw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGNEeXVhdVB0
        c3Vjcmc2QllicHJ4allKSTF3VDl6UUkvSjFXVWdoYU5PUXpydXRJenpzRzNDcVFh
        Y1poSnpFSWtBN3hydjVFazMyc2R2U29LYmtadEhBZVhvUVFxYzhBTVVrRUdQOG9o
        bkY0eGh6Zytvei9ZRTlqVlpvdW9HazV4YldodkQzVWtKbStoU1pPY1NNTjNLOEVL
        VEQ4RnJ2SE8rUGszM1lWZWdtT1FpcklZK3g1emJsRzFJdXovSWg3a05VT2VsaE1r
        aUdHRk51WnJUMHJlOVVyclNwdTdzeGQ2c2RiUFR3Z3NseVBoYWtJTUZ5Yzc0Nmwz
        bW1GM3JsSlFJOVhjNlEvd00wcTRVWmRFQ0NYWTFPVFk1ZHRSeVdhOTJVUkxYcm5p
        c3FYR2NHNTRDZHd1cXV0blBJQlkyWE03Y2FYL3VIampReGtXU05xUS92OXg0cklj
        aFl6bkI4bmlSWU1SMVZyVTBpTG1XRDN0WURhM2xwaXd0dWtKZkdtSEdaZVMzc0Jt
        SjZXNDlhbnliREdVazdlc0d5TGpZUkt6YkhmNnNEY0oxOFFpNkIySkhwWjZTaVk3
        cWxXQ3hGMnN1NmpLcXNRYlZLSDZxN2lDS2pEWDQzVjNadmVkZE1nRzBXT1o0ZkNZ
        WHhFM3hCQlZ3MU1uM2d0UmlsWkQzRUw2TnRFK0VCbFExemgxWmdpcjZzOEJXdkpV
        R3loYzVCdEM3MkUyb1ExeXY4b1NSNUpjVXhtb0gzYTQxU2FDWnlTc1ovZnhDKzht
        UVpUNjJuL1V6RDZCa2RRVjBzN2JHeVBLNjN5VE03bnRtclFmeTJhYUtkQjdkNEpK
        YmZuTGNjSzlYd1NwUU9DNHo5cjRKWkRYcUYycFcvU0h4UmgxZTlYajBYYnRWelRS
        clNGZmhpcFhWZVdrajY0UUxraS9WZ1VZdDJwdXRweXl1NExIc05vREo4eWR4Umk2
        Y2RtK2ZoYTR3U0ZGWG5mVEtWNlVPUjdFUmFIRXlDVDdxQk9WMnRDT1M2R2tRN0pR
        STFaQW5NU3F6SWhYOTY0MFdCOHBCTFRzNnlieWE5dDRBTnVwWStZcnI4UWNybGxp
        cnVVOVg3bHRVUGNKRjdGOEFGNWt5VzEyWVF1QjJGZE1CSHl1U2l0VWtxZS94SmE5
        NGJCYVh6M3ovZUlhVHRwK2tGY2xZMVZmdU9wTkZVVCtyVTUxdWIraHVWS0NLU3VZ
        WDd4VmtaYzRvTkxpYmhzeGdwZkNPVlZ2TnpndEF5RVloaTdVL3d5UFNHMUI1SnJn
        TG5DVzd1S1V1N2JFTlhQcWx1UmF4R0VMQ2Fkb2s0UUVNNDFkcjI3N0picEZyZGZJ
        STVCMHRFbTBLdHdIMzFoSVBHRzJHaU9lb1RHdStHL3FNMkVHRHN3YTgyalkvOSsv
        eFN6bElIc3V6bVhNZVVDYnpEQlYxR0pGQUUzSkRPOVNuTUhXV20vSnRVM1YwOHdm
        MVNLVUxNTFA2ZFFQMjdwTHR2L2E0SHRFaGZrN1c0Tk9QSXBYcHpHN09naUVFYi9p
        cXhMWUZaS3hEQmg4c2VXWndXRXZuRFUvYUVEVE5VYXFBZDRiRUVzMDg4cDF1SFEw
        L29vTHZ5L3IrMWlVeHU5cWgwM2QwMDJ6RzFKQWI5RmI1L25vNTF0dW5kZThONllF
        eDB0TDJhcUFqU1FkMEJ2ek0reTJGY0NWOEkzaGJBeU5sOXhOOGo3RFFNUmd3bXZQ
        dWlkODlsd0xqT25MTGRBRG5sRHV0RzQ1N0pLalMrTi9JZmExa0pQQ0ZDYXA0UG4y
        UnppV0lyc0gzZ08xTE1SRkNZWTF4ZTgwSDcxL1krc2FrazFyVzBBbmFXaDlKWnBE
        MUdFUVY1STh1TlJVUWFrdi92ZFlObWd2Z1lKdEpUekpzQ25DY29SM1ErTTkwalI3
        OGRRTUNkL3oxN1FGb3NJTExobUtUSmJiQmtWemc1Z3ZkaXF0RjVEeGZGMFFHdwpx
        QTJSNHk2cjlmZERtVlY1MVBJTG9sT08vRjJXSkkzM1Y3ZVlLcWN4aGNrCi0tLSB2
        Y1Rhc25obkM3dVVOdjNnZE82KzBxRzZTbHBXNkJVRHp0SFE0bDd2bSswCrSxvMDe
        AXtAb8kOb4WHUdXV5IPYrDwqQhd8OOwDm3+DLnMQ2Kb1W+Jys6cv2P5+Og9pCgvz
        iWqv48gHHTy8T7k=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T15:52:27Z"
  mac: ENC[AES256_GCM,data:IsGMNilvesasQYoOGaYh25GsX/W9dQhz+x7CIQhu5G0G/P+3a/P4YusEo5VS54MpB6u2C1Km1En+7dLZrjwionWiX5kNRjy58zFoLRx4P/8/j2c7QsYww3vnXINfFyHewuUCrsCAj8r0NPlDzd4EcbT6Ls7mYDcoPnNnm8+ecio=,iv:e2z2V/Ah/486TqgwmkkF5MEylwwmESwpldlxYSyeNds=,tag:2qEzPko9tO6i9rEFxr7GJg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
