apiVersion: v1
kind: Secret
metadata:
  name: homarr-secret
  namespace: media
stringData:
  SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:mwkOg/SuWAWVZySuzKyRR1K+TjcqvSfAomgGZr+iVvcuVp207lYSDg2DX2CCmi9NJYWiZRznV322Mc/UFyIpyQ==,iv:cXHxDOk0au1chijzmP4WV7n5KhDjzKtSugjMhg2yFvI=,tag:j5hgTSlhXqTb+ncB6xBbzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpzUkpuYnZL
        eFdLNndYMDRxenJRUHlWZFNaRGNDdEg0YVIzVnpGRWZwZDRlY2RwNFh0OHZQMk54
        TUtSZmRFbkZrQ2w3dlJrK2JNNkRyN2ZrVy9SakhiUXMvaTMxMFM2bzFtOUoveEtq
        WHpITklOYmNNTTJPUDBmczFkd3RFSDdBMG9KaWZkeVJxY1lYYnYyTDJWekd3OFNv
        Zlg0R3JEcCtzcERnbHFITUowbzFYNHhXcEUvQ044djc5dkQrZTBKMTArSENvdWx1
        NzVPNUJVQTlqTVpIRWZ2THVWU05GYkYxQkZRRFdYV2k1QTVBQ0NqSHpTalh6NEwv
        Nm1DNEJ2NVo1b1cvV1VvZHFGa2piN0RLS3lpdENkRDRYWGdoY3drTXFnVUxGMTlT
        M3g1bjFOOEhmM2ROcDVmOGVtMVVvcUdaQ0RKMmMzcVZNdkVzeGV2dFNGeUpGVFZ4
        NDlTTlpKQXpjUnBtQlpwbHlXdXZ3UmRhSVowbWNwS01TNW9UcmRWUW92SWw0Ty84
        azdJcnp0Y1BYUDZHYnJ0Wm9hd1VMSW9OL2Myanh6OHlzaFVHOVJ1Ny8zU2REMHNK
        anQ4MWJ2WjlpeHV3R1V3YWROZXJxMVUyL3Q5a0NwSTVQMUtObVZMK0VaVno3WGxu
        bjZKWGdHTzJtZVMvVzQ1RlBDSFhMUWtLVjRlaTYyY0RHOHN1LzUrZkRLa292WWN3
        Q0dFeVlyV3dQWVZOUmt1dGl5OVpoR0ZqRkRRNmtyY2pkR2U1MUk0Q2RIUHRoMUZr
        ODRMdjNkV3JSOHdwYS9XSExsL200djluNXdxaWJ1MVVJU2x0OXNjTTFOMUZONWJm
        M0ltdERYUE9JOVpaU0xzVDBvK0VyMjFhQjZMYzhiajhTaW40ZEFWRFM3d3lHQVRQ
        dWtZUzdzbWkxdVBGTXNLR3JBeHBHWjhpa2dtSHZRa2FjZUJWQ1ZkQWRjRldjbytk
        bkpCTUpZZGVNWUF1VHhPSVo5TVpWcVdBc2FCRTRBaWdoTjNNcE9CMzU5cmxvdlhO
        akt2dlBJVGNrdXY2REZSRHJGUEYzVzJrYnFEVU5OL0xDNlBCc1B6UWZwaUF6ZllY
        WHJwSk0rbGJCbXM2akJDc1g2eFpJZjY2M1pTNlVQZmI3cHJvckxGbisrTlR2aVAx
        eityWldMempkcTFzVm9ZbWhVTW1sdGFmMXduMWdCNXpmdzFmVjM5eU8yK2NGdGtt
        MXlSbUNuZ1lSZUhzeU10WEtoUWFqWWYxcTdBejhpQnU4WUVzaTdvNDFSdzF1V3U5
        SnpFOVRLc3U5aDhTQll4N1dsaGpWZ3ZKSzdKOGZMRjk5UEs3ZXNXdHU2aVpQZDU4
        Y1Q1WElBM3IzTU9hUnh3QjhJVlQzajkrK1NUVHcyN0Z2T3ZYeXRtYlJVU0RXelAz
        Q1ErSGp2TmpnSk5JQWFiMDVwellUNktmTGQ5cHo3UkVSWmlCQ2xNd0NJejgxU1Mr
        dys5QmMzUndTM3dZWTBzSEh5Vmt3blg4bG1wR1E0cndaSVhRNStQeGZ6a2RQR2V3
        VUs3K2dkakhoZzBBL1BZRG1SZDB2dUlBWC9Qb203eXBVYWwweUJDTnlKeXYrRGEv
        NnE3RXpWNzBrbkpRT2tKejRLNnpmODZ5aDJSWW1xTHM0c3lzM2FUVUk5OHZhbm94
        c1ozS2hvZ2tkR0hjM2FSZ1dTU2swWGhYYmIwUktLRUhUMDl4N1VYNmhONzJBNG9j
        bWdhQ3BNMUc2NmpOT3Bvd3ZoWkI2a1YxMUtLRnJUcmxhLzJjTkF3MjJmUHJCMzh4
        V1JqT3RJcTd6OUI4bDlTTWJCK0o1bGJkamFvd3oxc21aa0d6UzJ4c1RCR3ZYVHVk
        MVhCdk03TUlOYXhWUm5RaG5pcWUrTHJrcDUyNUE5YTdjTG12QUZ3V25ydnlJcDFt
        b2RHSXBQb09PR3VSblB2cUxTN1J0VU5PdVp4Q0t2cFMvcUVLam10ckhTWWNjZwpm
        MllTcWJjZk04UjBNMS9WWXdreERIZ3QvcGVaQjQxOEE3Z0pSVkUwMyswCi0tLSAx
        U0NibUdhYVl1NUVCY1pOVEE1UGFZVzFYdnlEVGs1aU5LOFdUOUhEdGs4Crwe++VM
        SsHQp1B4DI8UUvK9UBCN/KhgrAeTi+3GgKmdUGboH+qi8DwAuobiOHurya3EGrsg
        7lGEsy4UEVuNYqU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-08T04:34:17Z"
  mac: ENC[AES256_GCM,data:vCpKjk8Tur6Z9dtX/hg2lmi64S6MuLHCiDIQa+wdeWMb6aVRvnpWVGMy5LSycPIs4E8GEeIuhq1gchf2/SJDqDRjFLduXXR9XUiOZ3OofckzmH8SkCFqb/1ddJw6Oo64/Nontg04/curJsS3S3Lgv2vomHrIo3xdhhJM2nATrXw=,iv:w7sepmIWENRfG1HZ93YOVN0DRcpbKTaOYqBoVcUN4Gk=,tag:zA0kU5OhrJxC3S3BbniApQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
