apiVersion: v1
kind: Secret
metadata:
  name: firefly-secret
  namespace: media
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:cKt2oZ791cm9fEDsxecAaqVzgt3yX39T0D1OKZtss/Q=,iv:FVE9RyWd2Vt6ru2Am4Ixuh+HDfsFwxJrYVXo5krpy0U=,tag:OjhynntpkKg+V7qluGEFmw==,type:str]
  APP_KEY: ENC[AES256_GCM,data:n4k/3QgPct1etKO7OUEDqV9YjhgmG+TuSge12/tN2zE=,iv:Bziy3nc+FVpxpHIRJsWU3o/prL1JZJR+KTdsUyrAupg=,tag:OCDmEwIK2yJAombh4xpFXw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:+gPeFHzhJin8G5oHqUl8+id6acCxv2tf33gjxfh0EDs=,iv:9WNFW/Di3nKsVYEwRBgXqxTMKmBzght8YRLKdrA7BAI=,tag:k6QkdSQuKFZELjU7tMbNXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGJKKzN1dEpG
        NStZdk5YZnVOeHAyeHFTR0xZWmJyOUYyRmJBRTcxSFE2OWE2Y3J3K0QyRCszbzFN
        UVA3d1B3dzVWdkFrY3pYT3JGS0NqNEV6VWhNNWxEMStTZnJVemxYMkNNcG9qSVJZ
        bkdBczdGdmJBcTMzVjlEYkMzYnpKUnNEMzhxaFdadnJNTDhlbnJVMHVmYy9MeFhP
        OXpmMk9laXpjN0hqRjZudFNLQXV3cFdPSzYyV3RZNVpMRzdiY2szWlg1dDBna3dP
        NFFyWCthMG5paVEvSWNBK0RmK1M5K1BYZWIwK3hXTmxnODhtc2RpaGNaYlpVOUln
        ZnI2RDJXTk9rTTBxQm5QR1VQeTlsYnJONUtMVXRVZ2d2Mk1tQlM5YlRSdUl1N1B3
        UlNIWDBUbmZ6UG5qelhkSlZuaFNxTkZPUGVMdndnbnFnem9TL0RaY2V5K2NRVCsv
        bG50M0tiQmovS2JYZUhWeUlYWEdtVnJFWHd3ZVdxeGdhZ1M0ZnJHd0JMRUZ0WkxN
        WXhkdWRQWWRRWjdhajcyOWx6SEEzS09lNk5mQlNXNEFLTk55by9OM3VZOEloN0V2
        OXRsWjRmRlNySU02WDdKcGNsT2F3NFRIbVdES0Y4YXcxdUt2M3lYQzVLcHpRdFd3
        dzFLWHAzWHJzdjlCWGtlYnlBWHhic0xmRE92SFZ0TUMvai83NEpKRUlZeiswRmhU
        WkMzbGNaMjdLSFBlRW03YjFqeDRzRS8rSTVQSytzcytkRzlCZVc4Y2pjNE9qNU9B
        LzcvWUJHb0VxOGxvZjI1TFRnUmcrN1dpQ3Yyd3BLNGs0UE9wM0ZNL2FZWStIMGlk
        MFlQVWZUTEdPRGVkQUZjeXhxamZtR3FkdysvUlRqNzdINzJZNzI0T1J6cml2QmU2
        R2Y5ZE9odDRQemFIUGJqcGxJRG5SNEJXUURJSmhpS3lQenJkeHhVZHdGaHUwb2g3
        YTVSY0liblBsUjMwT1VKUDlvaFFSeHZDa1hMbndaSUdqZXFETGJEZmw2T2lVKzJn
        T0VmUDQvNFZ3Qnk5cEVBdmR0anpkdFRSeHJBdUNFRXJRVFl0Ymp1QjhnMTZkSFZO
        MHJmUWNQYnJtM00wb1JFRU9PRk1DN0hFQUpPWDd6NkhCSm91RTdLUnNGbUtwME8x
        SlFaZ0JZKzlQeGVjN0NoT1FtMDVjdEZPSitqYjFXZXQyTmlGQU1aZ24vaWwvZ1NB
        ZnZoNzhFeDlFZmhxRTRTejlLTUhXTHdzTnhtbUhZQUdiNklMWEE3MjhNMEpPYU5Z
        TlV0ZVhUZkhSbDI3WHRMRnEvSG5nZmVxRkcwQ0hQL3hOYXYxRUNISGttZ1Erazlq
        WjBSYStVRkpVZC9BY3VWRU0vUTNySVlTN2FwanJpS25mWUczb1JSUVZVaGQ0Z0gz
        RldmWkVUWlpsTFlkemZOWlVMUXBONm9iTURheW01c1ZLZnREMGtZZzdDNEJDMzZl
        YVk4Vk9pQW9tK3RQYnZrZWRFQStZUVhPTyt2Y2ZYazJGaTNGdHpkckxCclJ0ZWla
        NW5NdDFhWXplRk14V1BvQUNKWUttN0NHRXlGM1p0VU9lVzhuZVU0NDNZYmY3QXA0
        S0dCVWlFejVLZml4WGVjS2pSeENGdXgxc2ljeWF6bVFucmgxRkkvMElFeXdjQUdv
        NUZ4VHE5WWlsQ01YcmkwREtOVWttQWFlNGcwMW03bGdTUU5IbmRGQmQ4dVZOL3Fa
        d1JqRkYveTRUWjkyNEoyVFVsdEtZRXFZWTNPeHVpMEJuaHgyWDkrVEFOYjhyRHo2
        QkVWU0pZM1YvejU3ZHoydGRhdGQya0ExUTdsUWp6ekRPTUNuL1FNT2U1eWYvbEJt
        Sm1OWWlsTDdGWkNDeEVPRVJDQVV3NHoweWxiQVBNNzBGYUU2U2I3SVNhZWVxS3JI
        NGtpSi9KYUV6Skk3bVA1cGhCMmRrRHlHd2Zyalh3VDdxazM5MDI3ajB1bWtFZwoz
        RUtwN3JuK0NieTA2cXlSZ0tsczFKampQa3lQZVhHWExxVzBxM1dGRTZVCi0tLSBP
        L25EZUFnV1BaWTNOS1BQNHBOOEpqVFBsMUdZanozVkE3VGtnVjVhYkdFCu8XjW6z
        dX1hZvxn2iMZS1ETaNdqhKn6X1yO9QyKPriZEe/l3XFkx/Fsy/uRKeFae3NbDOUZ
        OWDODhazSrGiifM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T21:24:33Z"
  mac: ENC[AES256_GCM,data:YHmivXcQAfwZOLL9GE1SLRcT0yyZsmQP9HTCVEh5sgefIOTtL6gxRE8SAOmt9fssKoa+UcOycXuFZCHxUUXAL/aq6/zJU14VNcN4DF3H2z/oEbU7L7r6XgKFnEBNo/druT1UmyAHqfMqJ4SC2OrxArS0yHWcvoj3iA6+tNWcDw8=,iv:SMKiWV8u0Bc8dTg8VZWMU7+VIi567XaAWo4nz9cQVjc=,tag:eW7xgHymmU9CIadvnLXNSw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
