---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-server
spec:
  chartRef:
    kind: OCIRepository
    name: nfs-server
  interval: 1h
  values:
    controllers:
      nfs-server:
        containers:
          app:
            image:
              repository: docker.io/itsthenetwork/nfs-server-alpine
              tag: latest
            env:
              SHARED_DIRECTORY: /nfsshare
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
        pod:
          nodeSelector:
            kubernetes.io/hostname: k8s-worker-media
    service:
      app:
        controller: nfs-server
        ports:
          nfs:
            port: 2049
    persistence:
      media:
        type: hostPath
        hostPath: /var/mnt/media
        globalMounts:
          - path: /nfsshare
