---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            kubernetes.io/hostname: k8s-worker-media
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/jellyfin
              tag: latest
            env:
              PUID: "568"
              PGID: "568"
              TZ: "America/New_York"
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096
    route:
      app:
        hostnames:
          - "jellyfin.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8096
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: jellyfin-config-lh
        globalMounts:
          - path: /config
      media:
        type: persistentVolumeClaim
        existingClaim: media-library
        globalMounts:
          - path: /media
      dri:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
