apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jI7AOptoIT8y,iv:2VQnpKD7QBWUp4Ew55DqAND0SLCWXQ+N3aGo7eF9+jo=,tag:6QGxMzEmWRZnLSChg9IqVg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEdGMXMyMFdn
        a0lEaEZmMWVXMlU5UUZMTC9YeUpLelRvUVFhNG9JVTZpSzFTRjEwRXIxNEtNckJE
        aFZac0hvQ29hUWpVM1hOczFxMlBUZzBKd3VidjFGL1BOWGd3TmdZQ3ZNS2duYWg1
        M1c3RVNRQmROcUlDZkRhaDVUemFWaHY2N1dzeWJDQWtYMzBOTVVFZ25MekQxS1ps
        ajJBQnZIRFdKdHBSOVZhM29jM2xrak05dzU2VS9WeTk5eDFsSk40empBY0hUZGc2
        M0huVWlEOHRNUWVxZE83T1NHN3FwN0l2amxKdTNpNjlKZEJ0N0pGMXcxR0pLajZ3
        b1Z0ZWhsL0hib3RoVy80TjI0YjRJZG50OFZmMVFvWUo5ZWJwQlZBeEdjYTlPUHdY
        cGlNajY4c2FFRkJZbk5TY3VVQUZsMUZNS09sVGNlanhwNGwzcmU0MzRWMmE5a2tz
        VXIzaUtWc0pLZmtZWkprYklEN0xqTHdlNlk1VUVmSXFaVkhRSjFnZFl5NGtTYitJ
        YkQvbjBWMjIxZlZHZlFudmJrckttcGJjMlMwenIvSzNIdGxXMmhYUG12dnpKZ2Z2
        MEVlZnZIdy83bFpaUHpKQThxdzhyd0VVZ21IM0hXa2JZVUpQckdOLy81MEpuZkZ4
        OW1VenpnZVFFMjFCQllXck9iTkl0elZaZFd4KzB0MzhRU0F5MXp2d0F2WmVlMGdv
        MDhONmRTVjY4MHhHQ0w2OTZ3ZjRuN2tpMGd4QW94d1ZiWFY1THR2UXFtcGYxNWNR
        MXM0K0s1L09BUm55eVF2NEcvUWxCR01HOHBSN3JuR1RJa1pzNmdQV3lBSlRHYStD
        THlKU0poU0hlSGlyZTFVdzVxQVY5UU5GOTVDU0YyNEFOUE5mRDRwZlhsWldNOWFW
        MGpZZUlTdEZaMWVEKzd5RHZpUTI0TDRyNXE3eWlzMjF5aWxMOVFxRFpCL2JWM0ZY
        UEtucGIxVDNid1JVRUgvbm54bFZrdlJrbkszVnYrMjNLTU8yVWxqdlo1YkdvMmJv
        NTdQTGZjVVZnWmFyRDNpVTVUUHIrblRRMzU2MFNaQ1hvRWd5b05Obzd3S3oyRWJV
        UGx1Mmp1YlRTNTdiQUh2V0dTc3Nmeit2eDFvSWtJUjJDTkRicS8zK1FqbkFFeXFO
        bVBCNVdsbHY1eWFFVHRXM2s1NVNhcjYvN052OHN0Z3FoWnk1WkcrOC9pWVJUaTFs
        Sjl5UW9GV1FRR3huem9pTnhSZGpyaVZlbEZUWlovV0pmWW5vSHVPcE13eElmVnVG
        TEl6cnlMamRIK29rQ28rT0R4MUtlQ2NBOHRxMDlNaHFRTHFkRWFuVWRvTzZnTE44
        b2wyTHBjaXJMVVlBTDRNaURDNDlqSG9kN1B5dS8zdU84bzRsTmdaSUYrZFgzRTlw
        V3lKOHcwdjVvMnZKazI1UVM5bS9Pb3VrY09LNVVkTnFSOC9wZWpVZ1Z1b2JvMjdj
        cituQmJaSkNRUDU4RGtGY0NnNnk2SWFUZXlJOVBUQURML2c3N210NFN0dENocHFN
        emtoc29waWN2dlFmVFVLS0N0ak85OXFSMFk3YzJOb1RrNCtUZ0graElyWjFaYVV4
        ZDhSaVlTd3FrZjYycXlsb1RoOG5FYVpOYVZBL0FQM3RuRllmdFpQTXZUdDFOMHRU
        M05RQ0ZGbFRrVkxMcXFucDI5VUxQeEF6QndZektkZk13Tk5lZ2pxT1JjMXBiVmlC
        TnlWVVFIVEEzYVh1Ylo2VmJvdzVXbVdvQ2xrSnlRenpBeHh1N0ZzcjNyRzFrVWRu
        Zm0yMkZXN01ueDVnTmVsVW9pRHhsQWUxVmJDQkl2L0haZFF5eWVKY3k4VElFSTFm
        amx5NzBDRnB3RzBHODhGYXdWTHFOK1ZmQysraC9yMWo1RWgzc080d0xIRkZmNUJj
        SzBjeWovNHFaN0l2V1ByTVBEWGI2dWlnWDVmd1RCVG83MGZBcVA3YjZZellJdwoy
        ck9WUDhRODVBRWF1RFl2WjVvQnFQSFIwYU1xZzcxL0xVN3hia3EzQ0hRCi0tLSBV
        dXBWZ01uVkljemphbGkwTGg4NmYzSzFrQnZkTmNwTnd5QTROaXdGQncwCu1wpP6x
        yaZBfgClvVQdCKU4gwXBzNnP3QgtipPZ868W/EPz4qFVO3l5rZIP8MeZMfnXilsg
        X4HZsA1JSK0TUU0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T20:55:56Z"
  mac: ENC[AES256_GCM,data:Ak2YT0w9AGh4t776DZXT+CDhPTpdcUtKHXMqCHwuaDFL5TKgVIu7fEyrKXnP3B0Rc00aUpZq3ZXroQ5u3/Ra1mJxo1LdLzBWuRgS8PUsOYZOqc0xZxg6jxs36yMlfFYEjJYxMtKJ8l+Tf+F5J7PQ/bLLy60EKCvTInPpeMuTjA0=,iv:TvGvJlZzmXv/c62AZ5DfnPUG3Q7Er/sPZgxDOurN6hU=,tag:zzGIZdGCMbnOmV6nlSwznw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
