apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:H2sPUKOr2pEhdai4J8qfN0DRcZQDEoD+DOKvl7O85XU=,iv:JVRhRIJi2R21TU4Cfam/Vz3cr+xVEMz4H96hfxKvgs8=,tag:R5HaJ8N9UCKO8okdYZlTCA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpFZmtLcUNK
        ZnNKQ0dBNE1JMHZGUmZ0Rms2aWk1dVdYaFZhOERCbG0vWk1YUG1GeUs1RjZXSm9H
        RldYcGx6KzBxTW1ZVnNmdW8yMHNqT2JMcFh4N2R1bkJWWjRWVmRUSUFGdENuM2Qx
        NDFpeFdBVW1QVTdrVFJobmt6V3p2cUh5WFI0NmJ3OGlSQ0dzd3RkRUE1ZFdwOWFi
        YTN3ZTBwNnZTVi9MWTFGRkxoNDNxQUpScGtGQnNYNGRRdnRJSm5PMXh0ZlRzcjhr
        MUJ5KzVBVjRyMEN6YmdOZUZVdVUwWnphaFF6MWFwNXpLRFBXdFF2VVo2eEgzMUxB
        RTdaUThHZ2g0VHdkK3cxOXBaR00rWWhnZ0xWN2h1ZjJyVXUwKy9jUEVYY09uK091
        WUxYeDFQRzRJRElTQUlqczVDdEIwSThDcnp6TXpMcytYUStKNDFrNjN3d3hvYUJo
        NVluNTc1L3h1VXZZSktZQnN6em82TjYreU10ZmkxSXFySU4zWTFuRnZFeGdhZkl6
        OTFjSXdmU1VSYVdBL2ZpaFpmZjhqaHZvTDBYTUJFblBhdnYwZjE3ZmoxaGw2NFhN
        UmdQc0dSOWhnRkswN0dDMGpFMUFRR3BnRDZDRUM0Y0RYcWQvV1RsZENIQk80bW9K
        ZzZYdVYrZ0d6Q3BONkxxL051S1IrMjlzbGtkYTJVS08rSURkaDFja255MnhlQm83
        ZnJGSkRXNDNOL2g2ZWVEcnVDV1pSbXk2T0ppU25iSE5RQUlLUmtHT1lVNVgvRGkz
        bzdkQnJ2UFR6MjJEbTdXN0lodU9EWnpEU0FNc1l2SytvRVRPYndHVDBmbmV0RUpI
        RVFuRUJNeW9EMHlqdnpzNlpHOXRuWVJwNnU3Um9DRi91aElDYXJOTTlTVGc4UmQy
        eTlKMEFtbFRKM2Fodmxud2ZPZnZlUUpPcDhUYnNic3FtclRscXlZVXEyRnBHb2NB
        bWRmREZhbjFVUnh0QSs4ZmJwZXlURHd6RVo5S2hQdTVxM2I4VUE3dGZNd0pyWHdq
        eUlhZ0xWd0JNbVVRSUxiQjFDRWNpamN6TnV4NmFVbG92Y1p6bzFaekJ3VTQ5SmhO
        TFg5T0dDOTR1MXU3ajNweXhkWWdocDlNS0F1MERmdEQrb3pVM2pyaTFsVkc0OEVF
        VVAzZzQ0d0hiRmhsS3lKWGtyU3Z6aTdWaWtMQTE2NFp2VUlDNjdqb0dkRWErOUtI
        eWJ6Q2ZTeXdjZWhHRXdDbmdUQzN0eFdVVk0vWXhoc2RzNCtxdTZkK2REaVljcnJZ
        WWZnK2d0OEhLWXFvRjdNR1d6WHh6OTlUeWpEbUtzR1lrZmV1Z09ObExvTkt3OE1F
        SEtlZUV0NmRtSVVVbERsTnhPZ0loWkJvMS9UblNyUk1sZmlvcGI0dXN5bWRNeTM5
        c09GWTR5ZExzdHlnak1NbXpjTVAwdFVxLys3WUp5SmkyZWRYVWVTS2FTb3NsNkZY
        bWpoMEpIL3h0WS9rbVF3bjN5S3I1SmY3d254eHJXaDVkN1RBZWE4VTlWUWJic0Ns
        cEQ2THlLREE1SDJHMlBRcnBjUkZMNDBQV2FrdkRhYi9QMUtJRnlxMjBpczR3QXpE
        a2JmSUd3RXdKTklMOEZnQzR3eFpUTGl0QWxtMVBlNVFKUEpxelRSZXFzeU04UkVC
        eTd1UU16SkJYVWRDcStWWE1EQVJmSUcyb09EdEMxb1RoTGtNQXl1NFl0Y0NBclJO
        S1hjY0N1OGh0Wk9HbnFaL1ZJRWdybkpsT0FZd2prWGx3R0RiaHdCUkJwTXd0eFov
        VmxoQXZyMmsybmo0c3g3Qnk3UWc1Zi90K2Zpdzh0T1dnRk5Xc04xTE9hZmpyRjM0
        UVpsN2xsUnNxWnIva3ZaOC9BZmI3ZG1Fb0dVT0U3ODA5Qm11bGJoOTVIbWMzU2th
        N1REeXF3Y2w2bkQ4Sm1iUEMzeGNyaGVJcDM2cGFnZ3lNbGEvajdqN2x4YkVJQQp4
        VnVGOWpQR1pZM0RLOHk0eUpnVlliR0tyMG9xU0U2RUEzZzNkQzl0R080Ci0tLSBn
        WXVOczNUaEpMUXo5dW1lTUNVVURhTWdLTVRTZEF5L3lyRmsveGY4ZEVZCov0e4Q5
        pQsT5N7LmxdTN+NBzEaN5o57Uih7ZmoAXr2nm9mzs6W4ym1LnxuTlSyNWnQrL4Ff
        U+bE7xMd80DHxxg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T20:55:56Z"
  mac: ENC[AES256_GCM,data:mDRPG/rvbQiZFqhM+lrYAoYxvDOgTGDYU7flZ8KogMaekv7MxuvhGGrWV5BYocgFHA59aFBftJbH8G68iyGlGJDM+XbSLZDND4cdT/NadHTz/t1lSgW1nQ3CRasVg8h1pFhmvEudIJRcTcH7MxrcD2tcz2jW18BDfV+4gqHh6y0=,iv:dcvWBby/yo3MfpeZNN/5wy5Sq6brsLHeHF0hD1LGiVE=,tag:VYIcU+t2PFJarnVCMn1RQw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
