apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
  namespace: media
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:YV7Rktp9rjD1KQkoCfKuYfVQEqxsNWfXYhsVngjt8MQY3yISjTP8mM6B0Wk=,iv:OsnVe5JBJzT3dp09er+UjPdii5CCxCPNvvQzg7QUDjg=,tag:5zPv3TVVCll/yd338so55g==,type:str]
  WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:OfzWnZXLxYeHdGkswC2vrXPaENMlxXNZoXWDkaTm6BOHFPkXWcAPZndy83s=,iv:mta9tnQTaYCZWxB+flgp1GY/a2foPgvkQI7Me8vZ6SQ=,tag:/1Zw1gDUUcrwEPoRHfXPAw==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:D/TveJ7GWg6vXF3YevpBtA==,iv:eklVzzoD/7Ef7FJZ0vxz/8AZlvStbEDgYzX0wZBBLw0=,tag:v2lsd+5wjo6YMztZT/08MQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE56d01ZeEVN
        Z21jUDBMc2krSUY5L1RIT3R2Rk05azlMUlRmSzA5eXJuNkllUkc2YVFNQ0tGSUZk
        bFJRcmVkUHdDWVorb3dxQTVhaG5WaUM1K2pLb1FGNXVieUtwUDJmblRHR2duK1ZU
        QU9EY3ZCRW14V2g1NkZIZ1I1YklsZmVsNEtUdzJkRmFBQ0lTWXVtbXhGalVORFY0
        cUh1OSs0cE8wRWdEWW1wakpnRDlEbENmNW9DODJONGFUR2NISlF3TWtKS2VwV0lw
        Y1F5Ui9SL0dCUDhnT2RQcXJGSmRaSUgySmwvWEVhZE56eEUxNWtxUk9WdzVjQU94
        aFN4NHFIWmtjWnovOVc5U1B5U2tMdDNPdkN1M2FBcG9tS29aNk03MmdEbGtoZTJ1
        cHZXQWlXNTFvSWRVaVlQU21zZnNvM3JLSHNUSUdWejRQZEc4NWdWNThsb1dOSFhV
        ek53SzB1ZEpJSDRVYTdNMU0zOGhPUWlVc2MwZzIxNWhnQ2l6TEQrMGhOSzhjZ1Zk
        cFE3bW05ak9mOVB0VGpqcDdCZDNHWTZFZE1VVWxabW9HU1Rpem9tc3FZVTFvOFVU
        Y1N5VDM5eTEyY1hLR3VxL1RHWENVWFJwL2JaWE1NMEZGRi9vRVZkS1NSRHlIc1ps
        NjNrcW11WnllRGU2djV4QVUyMWttWDJjSkhQUGVtYWRvWHdTa1hWWTMrR2RmZHlL
        NkJyMDJlNnB4bE1IQTRaU3BTcDVVMVZBajZDTnpUd1VCcVhMWHVub3BUR3Vobi9h
        eTVzUGFodDFRaTN0ekJrQTlTUTJkdWRYNnFFNVlWOEVVSlZVQVFMSmwyY3pZWlhr
        MlFTL3h1WnFUTlZaQmpMVlduSEplZW8rTzdZRHJya2xScGJWa1duTWhRNGhiK0tS
        Ukw1V1hFNy9uVzZXUHdVaHdtTnQxcll5QVhURCtwQ0xnQ1MxZU5hRmVmZFp3NGlS
        NkRzZ0ZRb2Z2VjdFZm5UNXBmamF0MlZFeXdCNjhDaHFQN1FIbEQzaHpTSElUbTRk
        U0Z5Y3E2N0NaMnk1TWNYY2JDb29XaEkxOHREUkQzVThNVWRNWXdMcTY1WW5QZEFk
        OUtuQlhQdDMwTXZpTkFzR1c0S3JhOExzV3B4YVd6Rm1BdURQZVlWVWYwYUJ2T0d2
        WjByakc4NStpTzVnb25UR3JPTyt4VkRmbE9FNGJ4dGlWWlA3MkdCSThWbXhycEFD
        YnZXVlVSS2tuN1gwd21hd0RlSitPMEZoeGR1VjBNdmliMmM4TUhnMEYyVHJ1RGNl
        amk0UW5QRkZnTjQ2QkxwcFB4b3pkcDZ1SXBVVWw2a2xZbVhZemxtLzZwKzVKejlo
        RnpTNElHWG05TjNrZ1lMMnExaG9jRFhKbHk4NjhhRnRvS1BLaldIblB0d3ZqeW9t
        VmJTUWQ2UnpTT1l6TUtyWCtBbEdnRmNqSGEyQ0Y1aEJUR3NJb1RCWTg0by9nMFJQ
        RVdCVzNlV0QyQW12cHkzdHMzaVlVcTNNSldOa3lVaUJ1RDJSUy9qVzBYeHJ6K1VX
        eDIybkdwbG0zdENUV3hHaXJlOFlGeWxlUTllRThpbTM5U2djUXdqWFVDOHY1S3N1
        cE50YkV0NmhkcThXaHlDNFphaXQ0TytCL05xaTlGbHBMa3ZHayt0RlRITHV6bXht
        REJFNDNzbGNQU0wrVERYWkVXTmF4cFNXVklCMVBIR0lLRjNGeVdqWXEvNmhpRmhE
        ZXZRV0dGRDgxaHVRVk5lRVFZZ2Q2eDdpb2pHb3RDVE9lN1dlQWtUZEx2dzZQWXhj
        Y01vbFlWbDErWnVtVzQvaU1pL0xUeDI2Z2pwcUVKWng3aCtTallBZDd5QXJGTnZJ
        NEd0dTJHVXNidkVBdnNrQ3JQR2dMMGNrSlJKZWFmTjMwQkZoWEpsN0pFVlN2c0Fa
        RklQdVFhYllMZGZ3dElyeXFNRXo1OFllTVpSS2FZNTdiSnpnRk0rODVLMFhKdwpi
        eUNBMVUxUkNaVmQvWEJsWnJGdUV0M2NDNk5OQ3YzTGtiN3o5aUtzZElvCi0tLSA5
        YSs1TTRxVksvN01xMDY3QTRpV2pjeWFqdm1MUTRqcWcyTzl6YTZRU0ZnCiBP/KWL
        Tth5B8xnS7TVB+Z/ZMlHS2R0Stw9ECZVCNNlIzVV0vEo2d/BU13XdFToAOdmBOmn
        k37FiTVzGX24DQo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-08T01:35:12Z"
  mac: ENC[AES256_GCM,data:nXjl7x/fBHBgmLPq9c00j5AdTSFFKWzHIheJ0U5yWdtjrQ7fAWdNWnjwSUpHi5iMO8agRAK4sNK52WepNzi9slv5DCgfZl7CK0ODFNUzhWsuwb5dDcmMDC5QC93LjTgUPYDaibuqscRof0+EoI+lWXqmkuBl6DhlutR2fA1IZgI=,iv:q950Vk4b0ojnlJioC+0S8nx6mY8onAkehr0+CQ5BpCE=,tag:tasyuLpeYX9qzxka6t9oMQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
