---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: readarr
  interval: 1h
  values:
    controllers:
      readarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hotio/readarr
              tag: nightly
            env:
              PUID: "568"
              PGID: "568"
              TZ: "America/New_York"
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: readarr
        ports:
          http:
            port: 8787
    route:
      app:
        hostnames:
          - "readarr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8787
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: longhorn
        globalMounts:
          - path: /config
      media:
        type: persistentVolumeClaim
        existingClaim: media-library
        globalMounts:
          - path: /media
