---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: profilarr
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: profilarr
  interval: 1h
  values:
    controllers:
      profilarr:
        containers:
          app:
            image:
              repository: santiagosayshey/profilarr
              tag: latest
            env:
              TZ: "America/New_York"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: profilarr
        ports:
          http:
            port: 6868
    route:
      app:
        hostnames:
          - "profilarr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 6868
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: nfs-media
        globalMounts:
          - path: /config
