apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: media
stringData:
  COUCHDB_USER: ENC[AES256_GCM,data:QAohzLzwsrg=,iv:MoksCwsuGs4YWjYt4CYMsbtSpdKhC3peizRJtRuBuNo=,tag:RPJzRBzXmgTtne5zxLcnoA==,type:str]
  COUCHDB_PASSWORD: ENC[AES256_GCM,data:rjqUmF8H2NALYAi6vPqs3Wtn+BVtivUFTK0g+WQBhgQ=,iv:0gL6y5+66StqPWGcY8OSaoIMcCNtpdBbqGE4FucM6Hk=,tag:/LmVrquVvCXICF/u78gNFw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDNmaDVveDdS
        ZmJFSE5qd3UvVENjdmZ4cmpzMGtlYTU0cDJVd3AvMTJucEc4UEVvZzd3VVlHVmxJ
        Ym1JLzZBTERNclpTTXl1RCtBN0N1V0xvVXhHV2dwL1h5YUwwQ3NJNEgvTzF2ZU5h
        U0R2OHJjMHVmZTZYZUtrbVRBTk5UMW5rMXNYbjdXMWwwblBqOC9MeGV5RHNVRGFr
        NUF2eC9jYnRmb2grb0lpcGxDMGhEWXBIRGQ5VC9KVU82NFY1MkIwU3ErMmJKamo2
        aGcwVnh3ZFFHcVdNK21zZzgxMWdqTGx1SytzNGhlR0JEUHpXZ3lwTzlsRUlLT3ha
        Q1c1bDBTZzNLQmNCRGdTL0owQWJ6bnR6S0phcnJ0c25lUnNEYW8ybkVpVlRlMlBD
        S1JVbzl4NExBUUxSUzBITE5sWElZT1VxYncwTm5ac2FhMElpQnYrVkFsMmQvTjh6
        blBENTdJNWlJOUFPR3RDR1MrcVIzR0hSNGxURmdCUnVKVkdEQlhzZUhoZ1daK0dt
        eVIzUytkRnArOFR1RmxjSTY3WjVObFJKMGhGQzFudUNnZjZ5S1Rrb2RFSDhyOUhK
        bDJJQ0VCSVNObFAwTlh2NFZjNUx1SDl6TldKU2hnUEpFVkNSWmdSSmJ5TTNMMElq
        YkxIbGE1d04vMC9CNE5Kc1EyL0p3ZWVKbVZtZU5mSjRyTDBWMWFKSG9GMlFKckwv
        dHllNUs1bGNNU29CRHg5WFpHZ0NISEcvaE5WUVN1SHNXWGliRG5xTlFWajRhQ3dr
        U0wxZGYyV1VIenZoRi9VWG1nREhMcER4OXlVSmhjZm5uN1dBRlJ3Mis1MjQ2M2xE
        T29YRkpCUm02OUpodzlmQ0h4MGNZa0hjUVJ1R3MrZWNxL0p2RWxINFIwK3crOUpa
        dW5xYnBhY0VvcHpwYjd0Z1VzNlpnR29MVTVIK3ZjR0hpM1h1Wm80T1VYQWpNcGlS
        Z0Q0YjAxZlBxaGQ4V3lnRC9DaGRpY2UrRTJuNnRXVStHelVmanNrMUI0T0dONEtv
        eWhQQldrSDZ4bFlVS1RPakVzQ29jZUZSMGgxZC95SHZhSlBhelBJemFldU1SZmxU
        VklhWGZIYjRqTEtNMjl5bVFsTGRqaWV4N05tNk15aGt3YTdRS05DbXFOZmtzaW1N
        a2RXUHg0Ky9RTlA3RWR2SUozOXZKY2wvOTJpY3pLUlQvNzhIb1h2VFJEQWhpZzh4
        RURGWThyRFlPQ2F4YXNCd2Q3VVFwN0VSVWpYZ2FOTC90eUhONnkrbWdFQ0U5WGVi
        bjRTaUh3dlhmcTZOckNqL2toa05RRm0zTzlaNXFjOXcydWt1a2VOaE5iTWpYOGh5
        OUp4cmdZUXJSVGtvRzMydldZQ2EyTXJrV3N6MEkwS2ZWV3NNRG5lcjVrV0ovM3hl
        ODg5eXBWQ3VrbmsxNWJHRTZNU2ZOQUxJeHJBeWFXc01uNmIyWEVmcDdIbGZsNk80
        d01MUlp6SjZKWUh0UUVUcTE0dVppQ2tFRlQ5L0RVdW1OUzhLbkdRYTBYVktvbUVz
        NXoxU0ttaXhUZXJwNUdTN1hZa2Z2R3hQYUo4NXRMbmFZRGRiVU5BOFp1K2kvcS80
        SC9yZFE5QmFIWlRES09hMHZsMEtSbm53c0J4TUh2S2xMS0Ntb0VTc3hOWE51dHJP
        TG40MUtYQzFCUFd5RnpqR2NoRmoyb1gzSjRua0grd3pKZWlBTHhIbm5CblJBa3Q4
        cko3M3ZDZ3NVNlF3YWNaamJxZHRKN2NUd2N5M3B3NEpkWTZCZUhNV2l0NWVycjhL
        TUFvV0lTMWlEYjNld2dlV1A2SElSS0JwbVk1ZVBKQ3RySUh3dXhkRkRiV0E4eUtz
        QWowT3dEb1Y5L1U0eUVqTjk5MGdwVnBqZ3p4THBZNWxBRmJrVjJGT29HeEl0WFF0
        RTA5TjJEeEJYamtTbVd2ZUY2Nlh2N1VtM0IrbUFjZk84MFV0OS9KVm1YTlhOdwo4
        OS9INFZuUUJiN3hFNDZBTXF4aHdCY2wwWFRkSVc1bTU4bVNNTE9LNXVzCi0tLSBY
        elRmRFJJeHkvNTlvODJDZU5GY0ErK3N3dlZiL05pV211QUlYR3lPOXEwCuSejtDp
        40TFjEGTyUf4azeaGt55CQJ/JKfeEYog2WbEhuVkjbqhJDkjTl7F+veqp1i0YaBg
        kQcxsjfIP4RnmbI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T20:56:30Z"
  mac: ENC[AES256_GCM,data:kEH4y2F4hQCuQCjWw9OvVoiRimOhx+EIp6nTa9rYx7VFbkm9KTiIcTdPGOYUuDSQFy3mTiqUKsUV/1vs6EsQhryNb7aCMXK9ekIDmgjxLlVWfK4yT6ZXf1vuix9R0WkTOjPqY1XicNT1hKmVcfSBA6Ey6kKrEvs4MfW+AeEDT24=,iv:8STipdZjmLmYvGfIDgi+JMU7Y7qMdJt7hQOQMEsvPA8=,tag:yvDZ7yJnWr8WfY7isoGurw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
