---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  interval: 1h
  values:
    storageClass:
      create: false
