---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: kube-prometheus-stack-secret
      valuesKey: values.yaml
  values:
    fullnameOverride: kube-prometheus-stack
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 256Mi
    prometheus:
      prometheusSpec:
        retention: 15d
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 2Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-media
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    grafana:
      admin:
        existingSecret: kube-prometheus-stack-secret
        userKey: admin-user
        passwordKey: admin-password
      persistence:
        enabled: true
        storageClassName: nfs-media
        size: 5Gi
      ingress:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 512Mi
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
