apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-secret
  namespace: monitoring
stringData:
  admin-password: ENC[AES256_GCM,data:lWtH+WwfL2OkoQ==,iv:KB3uNMu0iHKTIW2WFtxEzxBrT6dbq2aUIMDx+jxD7PA=,tag:AYMlBhEnqxfW0jFz8S4JsA==,type:str]
  values.yaml: ENC[AES256_GCM,data:D+3KV8iFxYmOlfwCaDNQCzb3sjNgADTZB0r6jV3K38iTovE2fy6WsVy1x47XuHbSxXYIylegsArJDemRX7OIa69hHKQMe/ovqDPNGhr0GuJR5skJje+6lRVeKy+ITWJe14ztZXARhsJZi/naTyuZxPsbathN/3uGlojUjUV2Uo/HwVlJ0HTbqydldxfJQm6oenNKZIdZCKwLhN5G1JQZJxmh7nHefPZkaI7rek0J3ogQLxmq51yYZuH3yKj6SgqCO3Zj7KtmnKiZylVv5ZkZU3gt1cs43j0WF23EPxBq5RERVYUzKJlnEaJvpcdNjU+IcX3QFQurDh10bollnxuocrUWjK/3c/f75GD7tPDyPZwt0cuRYXmvQBYicqfeIdXsGOFNY9G9IS0GFaXN61N7YslnyWiKPMg9V9mGzNzJ380CYzZ4/1XQtRjNRXLJbSlFFpnvX+pMg1cJtd8qCJ8BWuklp+JLLEzNOukVHZeD4j3JFjUGYA==,iv:Abr7pVsNjbhY1qF/hPV0wpszVOrSI3bQ9arvfxF87rM=,tag:1qWqesMN9nVyNq538+gkrg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDZhVFVzZmt3
        b2I2L3FOT0Ruckx5eFFPTzI4VG01TldGOHl1dzcwTFdhMWNZL2Z5cktBZStjYkxp
        SEVJNkhmZENHYUs3RHpsazZxWTdnKzdCNUlXZUg3K0ZBQ21WSTE4VE5KVlBaRExU
        N2RhUjdpdVNmTk1wb3ZqajlRRkNDVFRpYnl1M1d1U2s1dEMyUHExTnIrZ1FlczVr
        VjBTZHpUTm1PcHcySENlWmp6d0dUN2J4OEhHTmJOQ1JRYmdlV1JNZmJYQU9XZytD
        cGxTR0tsUEhyemZzc01sQ2tzelRmUkVSeFNOUjM4NHJCM3d6Y2ZMZ3NDNXJrZy95
        QXhHN0VhVUlvVzB2ZE5DSDlLQ1liSkpDTmw4QlBVQVd1L1lqYlUvQm9aZEJUNStK
        Uk9ha3lNYmlvZmd6VEpPcjVLcUhlaS9LRDRaWStPOTRSYXlkYUFVcnRmS2dFQ3Yx
        RXhRYllqR2pIN2ZTZHY3M01CVUF0ZFVYM3haNnhVaER2ZFhTMDB6UkdsMGVZS2Zj
        a0ZzRVFsalloOXN4S3h3VGFtRlpqNzJjN0Jac3prY1hQWWhORDgxOW1jSHUxR0VP
        eXFaNUM3dE9FU2licGF4K0VMUWNQaWxQYWt6dXI1cnFwOFZyV2MvRlpHREV3SEIy
        eCticy9jYmNrSlVmRmoybDd0RDlWZnRyMCtOcUREYnArZElBSlUyc1Q4MUxCV0VQ
        NlZoajcrNEJnaW9SQnhSSHBaV2l0UnBCaVZ2M28rWVFBbGM2ajUzMlBCT1B5cjVZ
        cXpESysxZExpMk1XNGdUWG1ORWVmS3NDODMvSzhXamg0cmZrS29jeXJpOFpkeWd2
        bGh4NU0xUEdEZjFpZzVEb2tvZ1BaSzhaTnFCeGsvVmNpYXlyeXArZVZSbU4rUjdL
        SmFTc24zeXBrOHJ6dEFlNjdYRTJWcEpCdkN3ejVvT3VJa1prZWh5QWViK2JSNVdz
        cDFlUk40bnRBalE4MHhJV0padit5QmVKNnNoVTZTUDZ0cjVxc0FWc3c4NzIwY2J3
        Sndjc0hRRitubDUwWS9Nd3NGUi9XU0I3Wk8yRnNic25rMU9IdDM0c3FFVitXT2pH
        R3Z3c0hueWo4UW02ekJaKzVkOFJXWVhiamluT3JHQS95SW9JbVd0M1gvaXdRVEg1
        c3JBb01WL3VFQUVwMkZjUHByV1ZxV1hPVkVJcUtqZkRoSTAwa0tlbyswUmoxQVFL
        WlBrU24wbkxjbHhkSVBRUzhGRlp3SXRZNnQ2N0F3eWpmR3JQV3dHSHlzNWJ5Qjdn
        N1RqVlJUOUVueWloZHp3T2lmQy9Zd1VpcDVvNWRLSEJpcmMxVkI5Z3NqeFZickNv
        bDl3a1lmWTFpVnBSWmIrakQzMFE3ZUNTcGxNV04rakg3cXRKMVVvS3M3Zko0Q2JM
        SmdKNWJGYUkyVERFcmt0ZXY1QkppeGVrV2R0L1Rya21FNmVmTDJTVEVjRVpiV0Iz
        WDJmYlhpSEx3eDVqVWg3L1R3LzU1VDZRcStrVW9CMlFmTlhNN1Q1NWNoYjhqWlV0
        akplTlZDVWo2WUhUc3M0Y0JVZmVqMTJVa2NTSFZtdjhmVzV1N2NWcWJkVDY4S2Ro
        aGtYa1h0dTFDTmhhN0pFODlzZlhiV0JpQ3hwSm13aFhIN05YRTZ0Y1lWY2lMdVVH
        NWltNlNHeWJ0cVFObllGRFdMM1ZBV0RaNmZ4M1BEcWJtYW96MDRMWEVHayt0M1Jw
        ZXhHaWtHMGFLRDJlekVXbWZzbnJncG9rVXpqQi82d0YwemVaSnMzT04rVXBvN24r
        ejBVV1hYWTlDcmg4ZERMUFVIdS9yRVFMd1pkbFZWT25lblk4NGNiVVpxUE9lYXlm
        ZDlSNzJNMStuMmxNeVVNaG4zM1VqMzI5REFRUE1jV245dzY3dlFPVDRDWWpEUHBt
        UzQ3WXZqY044VmJXREZxWDNwUnZzTWkvbU9Pd3RmLzdkZUx2NmNQaEJ0M3ZPUQpR
        dm1oQW1MYkNtY2V4NXB5VGsyUzV0WWV0NGFRSmNpYkgrMzBvTTd4cEhVCi0tLSBi
        M2g3S2NBUUh1OVhVeWsxMHpkTEh6dFZ0aDlLQjNxTFFRK0RVSE5DbDdNCvAEN+sq
        7rSDdOYqNl5aanB9enMz64phKt1KZq5mGBM9npZlvsfGkkJ0nNoKGuuWSHUY0mrJ
        oOL7bBz45xymp1M=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-08T14:51:49Z"
  mac: ENC[AES256_GCM,data:YoXpaHfqJaNT9STE/Yntui0EPZDHeEODWJoy/KFeJ86KlxXsnhnyfag5kIXDr1RwJGNKSxCbE3+IephpLbJZvitwDsp+aguPP82ThPrBlLl/T4Qy1JcYxooa/PVc85wQ+Fnt4etAcj/vw7NDi+kyLO3Wl4A5wPEgF3p/jv65PT8=,iv:MbFcrGh7xzedwfutE19o8Q4A1mHBuHhv57ykVVLE8tI=,tag:IVmfZQtgFUyZBuaAuC/qNQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
