apiVersion: v1
kind: Secret
metadata:
  name: firefly-importer-secret
  namespace: media
stringData:
  FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:z225mhhV70VioQCfW4PWW5kdI2rzXtVOCcykE1vYGtI=,iv:/y/wRstjQw1h44SWqW/tksNdbEH5TreGXoPTeaTVxRs=,tag:eSnS4pTQ8UEUwkISdbTBqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHR5R0hFcDUy
        Um9vNzkyMElhMUNaV3NZT3BSNTRyZ05tOXYzaE80ZUFqMVYxd3QraGN6Sko0SGVu
        OThhYnhyWHBtSWxNTmFXRlBoV3NmTis2cFpSRUZuSExVTFNPN1ZwblJYQkFoTFZy
        SE9RUmUxazB1R3ZQQS8xUW94ZGFNamcrL0lIVmp3bS8wVmRHTUZMaG5BOGtQdUo5
        ZUhyRk1iYmdJMHFtVHgwZnZHRDc1ZnRZa0QxM1BqVGpmUXQ1TzM3UHVLSHVPa2hn
        b2Ntb1JRVTFyM0xWMkx2VW4rRS9FUE1XcER3UHQ4YllvbEhkY1U3TXRBK2o1amlu
        Q0VRRE0xVHdlWE5KSHc3WTJJUUFhSWVuMTZUaS9zd2RZUlljcXlRc1VXQWZuSTNJ
        ekZ6ZnhpLzZpbUZ3ZUpFRTR5cWEzcG9Nd3M3ZHhNMGJZSmNuUk9qOFpJSVE2L1A4
        bVQ2QnFwanpTNWZvYnJNK3ZsTXl3UzF5RFF0MVRiVGZ0TmJIblVEendKQ3lSN0JK
        TitocTdBRjFRRlRhNC9IUFFqalY0TTdiRjFGMDJHNzdxdVc0MHdzYjBQTnZRY1N1
        N3RPQkJKRGFiN2pFcHdQNWk5OE9ZMDhMeFltNEF3TWpqc1lTTFdhMFJQVEtEVXo3
        bDROZHRkRFV0OTJ6UUp4OVdMNi9LQ3FGOU5JYTFJTDV5bDE2R2I2Tnd6cjBHV3Jn
        YmNhYTdIODlqaG5vdXQxQTIxRzJQVDNhQ0pFbnlzbXFudnd1VXRETkRvOW02cFhD
        V20rVFZmTHh0YXpocWYzMFhjZzBwbnYvMExDb016YXFoZExNOXErRjlJcUpSSlVU
        aHpRVlU4V3JJQzdiOEZkVmloWVJUOWh1NXd2a2ZJT21NNTVicWU5bWNIUFh6QzYw
        SFBQSDBMenFDQTlyTkprVHFEbFFSOTBzVFA1Zm13dVFvbzYvMHA3WkJmMHk3T0VZ
        UkdPd0ZPQlF4U0Ira2N2eXlnK2JPR0J1dTkzYWV3ZGhEUk9uYUU4dmxwNTJQOUgw
        bWJUdUIzZHpYM1hFSFlrRmxiNENZQkUwU2daWUlSMmtEM0xyTDMrZGEvakJnWE1B
        aXN4bnM5WDhhWmpPK2krcldpdnVDejZ5SWF2aWJMOE0zNkRzcC94dkE2NUVUazJl
        cFBrb0M2K0dabUFGYk5HU3hDL2NEY1NjZTJCdGFKU1VFQlBJQ0RrcmNGYjNZUDVK
        SUZXbkI1T1M3d21uWjJHbVNVeHV6T2QyZnQ1dE01eTJ4YW5NZm8xSEZ3Y3Z1S3VH
        QklxZEo5YXNTVmtMaXNMMlNKUHU4WE1sK3ZaTURpMFlwNnhaOGMzZHpuaC95MGtM
        SlpCMVJoL0NsKy9pVUtzL1NnNG5IcVJtYktQZlVCbjhsbWVGU2pHL1NOUlpmOG5k
        cGp0RHdSY3hSZEFwMXYycFpKaXpmNmRjYVJVU2lpKzRqM3d1N1N5Z1l0R29nS3ho
        Y3ZCRlh3QWU1clhzV3UzNTBPNWl1QmR0REpISjJvZVJwNTZ4ZXNDdTlabmhFbjlh
        cHMrOVVVRmRoeTVwN280UGEwR1JGWmJZZFVsNFUyU2hzZXFHdHZhV3VkT3ZiZzFF
        YWtmOTFBRHpwbHoxamE5aEFVeE5STnVQTlFNaVl4dGRYNzV3dmFFaGtvU0FRUmQ4
        aC9td1hDVlBCRTAwSC8yRkhXMElsUjlzRER2RGRsWkpjd3FuNTYxZExBbDlwd2k5
        Y3FUd1gzTGpBazFWNjhSelhKbzN0MjVuQk12aHFxdEZCcVB4cDJpTzlnb2NyR1BC
        NjJhWGdSZXlGUUNDRjRBamdBaVlwNGpSdTVXT1FPclNtazV6Ujd2RUttMStRTzBY
        T3EwRHgzcFd5cUprTkJHMlRXZUJHRDkxOEcvQklmWVlqa0hQUFduUmxPa2xjZE1H
        d2l2L1hVMzVlYXh1bnFZM1BqS3lUeWcxQ1JkV2ZUaVhtYVhqNnJWcUpUVGJPQQpB
        SkdsdWxuZFRTbmtkUlk1bDZ2OGJHNExPcVVZd0Via2pNbWV5SjZVOGdrCi0tLSAw
        VUt3OXN6dnlTNXZnelErNGJ3UHMwcDN1L1JkOHdpMmttN01Xb0NSUERRCsRDAbye
        7+xLbyPuKoY2GAJQcS58pwdmM5B+X+ay14DR+u/kcyXduYEjAAn+yzqEF3ILRL0X
        Hmn1Otvzy39qMXk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T21:56:08Z"
  mac: ENC[AES256_GCM,data:ZGy2hDLY+CdYfQ9UqBhO2mIIV1fO8Mfo4LmSZ70qoJ7+Yon5JuXq8r0bHFVwm3LYSXbzS0LK2mqM0uWZZKGYIDvI5hp/LTpYdKc2zTSbNQAQ4x9T5vlflew/uG+zx532WUYzgngd2vkuZisHKb7JY6+CpWqBVWbZr8tF42Ozjio=,iv:ydnODlZhZX2Kip2fyJlLWHegTsPhbyEQ0zbXHC3Eb8w=,tag:apngrXW8d6L5vTEkKL2P+A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
