apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
stringData:
  client_id: ENC[AES256_GCM,data:obEpn93aRcCCuoB/txsSCA0=,iv:SySAQBo8Oq4c7KWz+uYRRfLnkAS/ApSHTRLeACNhH5k=,tag:+Hk3qnktTUFo2jlCDrfTxQ==,type:str]
  client_secret: ENC[AES256_GCM,data:iT82N8EQZA66uJABnY6yhUSVZda/Z9q93nUIhuSD9shtaNDwjC5Z4ByO9PHByrceCN3jJ8Nxr7T1Y55bV8WitQ==,iv:5iNjPuHchH+Jnjem4e2P3b1+KDncHZv7osSLdnvZALw=,tag:6l1s+T7qenncd1Ow6cIF7g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFp1ZlpoZ1FM
        VTQ4T1ZDZmVBdzZDQmJIKy81aU83TkFWWGY0ZDhaanFnNGFDbkZ6OHFnaDlwVGgv
        TjNSNi9lSVUyY2Q3MTBsclJSRzJ0K20za2FsWFlSVkJNbzJKMy95b2RsVGVoRlVm
        RFVkSURzdjliU3ViTUkxMTMxcmwyT2xBand5NWlqVEdYQ0NGU1pLTTJ4RklvekNF
        RTNUREJxVytnbWxRRWxIUUVwZWJrdUlxeGpWVlR2QVVYMTNFRVlUV2hTeTA5cTAr
        YkNVWlIrOEJkYS94SjJHYXNFV3NoVEJoQ1ZMUmVLNEd5NUFJanhnUEN3UVgxa2V4
        M254enRBOWVMeXZNM2RRQzNrUGFxM29RUlpIdXl0eTRoNmF3UzFLMG1sQ3FNbU5S
        MEZGT2lsalpsZWMxM295QWhKeWZnQ05uVmtPMEhobXNWOXZqa1d0QjJJYkhvT1Vo
        Kzd0d3l4bStKUDc0R09xNGFhQlExcVd4QTVRU09PZWFaSU5sL2svNEJKNVhYOGgz
        bU54VGxBbTBlV2I0cHRFeVgzU0xNd0pZSVBrbGRVRHRzQUVIUkdYQ0dpK3dUNlJl
        ajU0RGJKdkhyRFJjSmJ5QWg4dW9pL0ZXUy9xcGZaNXVGelVGS1k4MXhtNmlUT0Ux
        K2o2MkgxdFBhSlpJMlFVYUo0UXNVQXNWai9uT1hJWU9LQ2ZyWFA5UTRpSUIwNXR5
        L0Zleng4eXNZd0ZnNk9KRUpOeUorQzVNY3orVTE1QzdjdXJXdUd0MUtDcjFrOVdU
        d2FYeUZlRmtaWDJ6SHlNWjZQc21xOFl3S2lPclNjTFQ2bXc1TnVReXErWHIvbUN0
        eVZHMDB4QkdjRTBuTXY4aThJQng5VWtZdXgxZnZwOUY2QWxHbmpzbnNNeDVtV2dn
        Y1V6WlY5Mk9Fa1A1dnR4ZmhVODZ4M0NXZUwxZlk1QkhvN1BHQzhpSWVZMnBncURr
        N29ZQXR1cm9PcWtEb1p3VE5tV2pNN05YZWVrUWtuWXIyL0RrdW5HWDBORFRRU2ZI
        N1gyZzEyVVlsS0xyL0FzRFhBc2VFa1dvRk9GQkEzOWVTRGh4d2hVc1VVbk5FUmFo
        WGpvK05Ud0ZIell6QjREa1M1Nis1NWFoWVZsMzAwRkhFLzJYZWNkZTFwUkJpVDd6
        VUVubFBobVFlMmdDaXgwVW0yQXdKdlh0cllZeXJ0UFBQRk05U3hxSFRKclFQZWZk
        aHUvVGNHUkFVYm9qcFdXNk9DaTd1N2NMcGRaYTNJTUJRVmxLa00xbWhuUHUwcDBN
        dEtlQjM4TUNpWTdBd1Q1M0dQdkFTc0UrZWUzaktXTkpYREF4blR4OVhrdjVQZWdW
        QUU3K2FOZ0EvY3VOazdqdlZoNnBjdm9QRnViV3VOZGw4b1JNaWFTbE9GZkc0VmJp
        YnNFbHdvNnRCTWxQK2h0UklhNEc4V2VhekV4YkQ5SjNFNjFNZ1JuMVJkOG1BTkov
        c0wrQUNFWnlYNkw4eFVtZVdCZVBlRTlNYXNSSnhRS0V5b2lRUVp6TDA4Z1VWOVBL
        R3VQZnkySThTU0hHUDJGdzVMUE9HdTYzNnVsaWVRWjRCRWxQQTBqUDR3cjl0ZG9j
        UnZwVlN6MG04OWV4TDgxanRaZGhmcWRuVkdTUlZiRllvcVZMQ3RGMTh1ZjNIN1My
        V3l4d05vNWNqQlN4MXZlck5GbHZMTE9kckxJVDlMb3lTcXdLSUhnUkdONzNkZVN5
        WGxsM0cwSzNEbU1aMXpZa3hJa1BydlczSzhKSmlzYjJmRXlVWUdwWlZvQTlIcHJU
        Yno5TzVWTW1zc1ZvUU5RQnBZNUlHVktCR2pmS2svSlJETXhNNnhndCtXOGxxTVlz
        NVJRYmNmaG5zQlVFUEcwQUZ0MmlKb0l1RWFyOWJCWVkyaXlqZHFCc1AxVlhRTGpm
        Skt5bElKQUtHNlhiN2FtdXI1T2ZhM1cvUjk3ckd0b2xFV25kMmRnTGhzTVNSZwpx
        UXRVdEk5VWd3MStySmVTeTFBRFlTWHJGY3BUZzZuZkhaL1hrVE1jVXc4Ci0tLSBs
        K0RxZmNYVjlLald3Q09jVzlpSzBwbEFpQXcyS04xSWNQZGREdlRGWjRNCov0wZ9w
        qqkKdfOvm9ySp7xzXH140qTiuDN5v51ZKfRynEoS0OtzaKtq0HZjtcMOBPe+OQ+V
        kp+YHiAELB40Esw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zzguewl52grp56jgk4tnkfzyljdc58rrpx8a99v9tx8fe35gvspfynvn28ju0wxxushx8kpllwuht7rsszeuc6ukl23vhxzkhn6mkynhzp4vvnq5p8ynfm9zt7v8z02cddfjevjjj4gd05uk0gqjpnmn4s8dchyvlfkxheyumfphu7f93pfdchzt5u7pj3vk5mesnxeffhmxhn32afagcjkv8tnmm3nfvv2ehr7l79nm8zdhyvjgl79jpa9sq8vzj644yp25tlr2ah9kzuklyqnnrg5d0zmc5g9hd0kzqlawsnj06nrwp25zvcuuvv7zq388evjqf90mzjysxmy5wqtp5akd0r2axdyqwzygzs2u5r7yy2teet2z897kdyvltyqzr2cpnh4q2krdznz95gc4tu3e72w8xwuvc45h2apxlstzu6yx7qzy0njjn98mwwkzv9ejxfqkgez4dtxw5qkqapxs5pqulxt67j6226lsc36qymq2lj5dc8s42mqzthregyrn2g5pd5dyr6xqz35kfm2xx2sn5dyrhk4vm0t2lp8t5g5lct6gfguq0c6k5vmz0lzm82gj27lr3fhg6gazv0eq6ntmjat2znaqv2lejkkgem6m2tfxt5s8zq8xlfgf36zw5ltn96mfypljx8rac4zzk9te3jttfaqpc30rh05dxhp6vucve4dcltlsql0n5w855sl2jx7rdwey76y58p2se2cvckvusjmwursg6uxy0jdf2vapgjmwlmp2nprt9ere0l8mpvd724pgx3jjzzsxn3fkngdrgry9sjmxvkvl5qk92734hxx2ppzwdpa3ugzjqljf44detemcnx3q7pzluewdh25jr5hhtfyz09l92fxl5u4q7zcuxp4m9a674y2s4f5cqefxax6203s2nttlshl48f8jdkw0fuqrfqgthyhzccm2kdaavfe3tx49hu63vpmcs4738wpau2wppfnnnw63tsklt0qw76djzw6mvlxvzyt885utz77v79895pclswmz8vh2tv4vgfumsdzpp9fudlnsxhgv22c4f9pegxudmw579ss3380zqh5qg6q3608anqsvaqy60amgtgy9s44u9sysr9dt0sqrxefe5q2v2mvyq4w4fs93tdyxhq5e9kgaqhfyt94gvypyt0r4zfuyedrdcd3yz58elpnn73w8ppneywkhk6r5kdu7kdzn3evh8n6xdqt8s6dwajgsc5ngq762k2d8tc34vfn075c4fc70dntzcm5mjzscwdkhrzggwkpm3petpece9qnkd8tpsdwem7nf2d4vtd66xcnqq9eq8ggmtfdwfc28u0440xdwve0kcwxxhsjt6fq62zs306cckvylv2xr35mwxvv9ur0m8406ys83s34fpxptmpuvlvthwj0dp2hh6yuf6xgypcgqs76x9gsg0qkex0raheudpxekrc24x0awykk09q5pge2nm5qe4yhqklz3zhjdw40yv0xzslutj06u4mn3ydh5zkn6ms38uwgclt0xhfn2fplgj6hrxjagtg92zarjevlny4vts0zzfgmnvt5m0nvjstwrdd5u3qccqedcxva5tqfzj9jeyfr0sj0rdptsvct8n8kqrmfsp89hu5ysup22kdnz6xmf056u2r4qqrgdefwp4v5kxyjr0pwv3vxmhzancuv6fxp5v0592l8m03argf7ck630l8a92f9ctsrcjtzz3g997yyxpjnrdhr8dpyhkmmfsftt0j49hhz3lfvk8l2ajqsgp2u6hsep4y2ykeam0e6fdglsj8zq5vywy69xsxf69q3vzmaxwkmmx5kuxlrxgzv6eql7eh7hutvqcy0l9065r9an80k3kvxqaqhy9cr2v7tjkesy94ngml8pcznnlkgceqtv3cnwjxlqpt0c42zmzrz9zuqkdfqf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T18:59:19Z"
  mac: ENC[AES256_GCM,data:4PcL2xYKL65IScNG3MaSHqcu1DSS3CRTHFUDBAQGNSzasv7E9Y+Kq3djZSaWCiziDAlTaN72Z+sXqwaRbFNHmZlN9SHOuL0dzMto79GEVzh28YgMxd6m4W0Z8dqMI2SeQFvNwTP+oZjOB2a7N8PDrGwXPQ2BdsLyE7wnMSB+Eow=,iv:c0hKVs6fxDsc2L0+w3mbR2ze++dMH9aiMhAixginD6g=,tag:HyBTL1gKPMUYb1LqMjc77w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
