---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: adguard
  interval: 1h
  values:
    controllers:
      adguard:
        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: latest
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: adguard
        ports:
          web:
            port: 3000
      dns:
        controller: adguard
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.1.244"
        ports:
          dns-udp:
            port: 53
            protocol: UDP
          dns-tcp:
            port: 53
            protocol: TCP
    route:
      app:
        hostnames:
          - "adguard.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 3000
    persistence:
      work:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: nfs-media
        globalMounts:
          - path: /opt/adguardhome/work
      conf:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 500Mi
        storageClass: nfs-media
        globalMounts:
          - path: /opt/adguardhome/conf
